<?php

return [
    'sources' => [
        'login' => 'login.html',
        'banking-solution' => 'banking-solution.html',
        'capacity-building' => 'capacity-building.html',
        'banking-talent-solution' => 'banking-talent-solution.html',
        'learning-management-system' => 'learning-management-system.html',
        'inovasi-program' => 'inovasi-program.html',
        'program-csr' => 'program-csr.html',
        'headhunting' => 'headhunting.html',
        'outsourcing' => 'outsourcing.html',
        'job-connect' => 'job-connect.html',
        'bakti-pendidikan' => 'bakti-pendidikan.html',
        'bakti-umkm' => 'bakti-umkm.html',
        'tanya-jawab' => 'tanya-jawab.html',
        'syarat-dan-ketentuan' => 'syarat-dan-ketentuan.html',
        'kebijakan-privasi' => 'kebijakan-privasi.html',
        'kontak-kami' => 'kontak-kami.html',
        'kurikulum' => 'kurikulum.html',
        'kelas-online' => 'kelas-online.html',
        'kelas-ai-literacy-for-banking-professionals' => 'kelas-ai-literacy-for-banking-professionals.html',
        'kelas-apu-ppt-untuk-pegawai-bpr-bprs' => 'kelas-apu-ppt-untuk-pegawai-bpr-bprs.html',
        'kelas-dasar-analisis-kredit-perbankan' => 'kelas-dasar-analisis-kredit-perbankan.html',
        'kelas-dasar-tata-kelola-dan-audit-ti-perbankan' => 'kelas-dasar-tata-kelola-dan-audit-ti-perbankan.html',
        'kelas-digital-marketing-untuk-bpr-bprs' => 'kelas-digital-marketing-untuk-bpr-bprs.html',
        'kelas-first-time-manager-in-banking' => 'kelas-first-time-manager-in-banking.html',
        'kelas-general-banking-fundamentals' => 'kelas-general-banking-fundamentals.html',
        'kelas-keuangan-praktis-untuk-pelaku-umkm' => 'kelas-keuangan-praktis-untuk-pelaku-umkm.html',
        'kelas-kpi-dan-okr-untuk-organisasi-perbankan' => 'kelas-kpi-dan-okr-untuk-organisasi-perbankan.html',
        'kelas-manajemen-risiko-operasional-perbankan' => 'kelas-manajemen-risiko-operasional-perbankan.html',
        'kelas-persiapan-seleksi-dan-karier-perbankan' => 'kelas-persiapan-seleksi-dan-karier-perbankan.html',
        'kelas-service-excellence-dan-customer-experience' => 'kelas-service-excellence-dan-customer-experience.html',
    ],
];
